### PR TITLE
Depends on lodash v4

### PR DESCRIPTION
**Pull request by gfx**
It should reduce 60kb+ of JavaScript bundles if our apps depend on lodash v4 (but not v3).

Can you review it please?

### CODE REVIEW

**Comment by finneganh** [comment]
I'd be surprised if you actually were getting 60kb of lodash 3.
velocity-react only requires the handful of lodash methods it actually
uses, not the whole library.

**Comment by gfx** [comment]
To be honest, the number comes from [webpack-bundle-size-analyzer](https://github.com/robertknight/webpack-bundle-size-analyzer) and I have no investigation on the details of the analyzer.

It says:

```
node_modules/.bin/webpack --config config/webpack.config.js  --json | webpack-bundle-size-analyzer

...
velocity-react: 91.18 KB (1.99%)
  lodash: 67.87 KB (74.4%)
  <self>: 23.31 KB (25.6%)
...
```

**Comment by finneganh** [comment]
Thanks for the tip. I'll look into this. I'm curious what those numbers are
post-minification.

**Comment by Antho2407** [comment]
I this branch gonna be merged ? I'm having lots of problems with the lodash dependencies, as my project rely on 4.X (npm is installing the 3.X version for the velocity-react module, but it's still failing)

**Comment by finneganh** [comment]
Not sure what's going on in your node_modules, but having 2 different
versions of a library that are included independently is supported by NPM.
velocity-react should have its own copy of lodash installed for it.

**Comment by Antho2407** [comment]
Maybe cause lodash itself is a dependency of the project ? Not sure what's going on. 

I tested @gfx  branch and it works great on my side 😄

**Comment by Antho2407** [comment]
Just for the record, turns out webpack was the culprit, and resolving my modules with the root ones in priority 😄

**Comment by axelson** [comment]
@Antho2407 can you give some background on how you changed your webpack configuration? I believe I'm running into the same issue.

**Comment by gfx** [comment]
I am surprised at the fact that velocity-react continues to use lodash v3 😲

**Comment by mihaibogdan10** [comment]
Completely agree with gfx. Lodash v4 was released over 1 year ago. Surely it's stable enough to warrant a version bump here.

I ended up here for the same reason: I was already using all the functions imported from Lodash v3 in my webpack bundle, but because I'm using Lodash v4 in my project, they were duplicated. Sure, it's not the full 60kb, but given that no arguments to keep using Lodash v3 were presented, why not bump it?

**Comment by vladra** [comment]
I also have problem with lodash. My project uses version 4 ofc, and I have conflicts because of this dep

**Comment by finneganh** [comment]
File size is one concern (but can go both ways; I'm not sure what the
relative usage of lodash v3 and v4 is in the wild. Fabric is I believe
still on v3), but if you're having JS errors that's some other problem,
either with the current state of node_modules or something you're doing in
webpack. NPM fully supports having separate versions of dependencies.

**Comment by vladra** [comment]
I've encountered problem with one particular lodash function - `upperCase` (at least from those I found, since it's runtime error, webpack build is fine). With `velocity-react` I have this error, without everything is fine

**Comment by Antho2407** [comment]
@axelson the problem was Webpack not loading properly the dependencies when one version was defined, and another one in a library (like lodash), it was merging the versions.

My fix was to change the way i was resolving modules : 

image

hope it will help !

**Comment by STRML** [comment]
In combination with storybook-react (which now depends on this module through react-treebeard), use of lodash 3 is causing resolution errors similar to #216. I fixed it for my storybook config by adding `'node_modules/velocity-react/node_modules'` to `resolve.modules` but it's very hacky.

Any particular reason not to use lodash 4 at this point? On most projects this will dedupe out.

**Comment by finneganh** [comment]
@STRML Curious. Where is `resolve.modules` being set? Is there a reason it doesn’t include the default `"node_modules"`?

**Comment by STRML** [comment]
It does contain `"node_modules"`. It appears I hit some new webpack bug here, where the deep import to `lodash/...` is going to `node_modules/lodash` for some reason and not to `node_modules/velocity-react/node_modules/lodash`.

I'm still trying to track that down, but upgrading this library would help anyway - v4 is over a year and a half old.

**Comment by finneganh** [comment]
What's the ordering in `resolve.modules`? is `"node_modules"` first?

**Comment by STRML** [comment]
I run a local folder first `["src", "node_modules"]` in order to keep a sane module resolution pattern without all the `../../` insanity.

**Comment by finneganh** [comment]
@STRML In that case I would recommend following the example here: https://webpack.js.org/configuration/resolve/#resolve-modules

and using `__dirname`, as relative paths in `resolve.modules` are treated differently from absolute paths.

**Comment by STRML** [comment]
I'm aware and using that, just didn't list it here.

Regardless, all I'm saying is that there's no reason not to merge this pr.

**Comment by finneganh** [comment]
The reason is that I'm not interested spending my time testing and doing a release to work around others' non-standard module resolution rules. velocity-react's use of lodash 3 is entirely within spec.

**Comment by STRML** [comment]
Wow, okay. I figured it's worth doing to keep up to date, dedupe with
lodash versions in app bundles, and get the latest bug fixes and
performance updates. It's not just for me, as evidenced by the this PR
existing.

**Comment by finneganh** [comment]
Right, I didn't mean to imply that it's just you who's having module resolution problems since, as you saw from the other responses to this issue, it's not just you. I get frustrated that every few months I have to respond to folks whose setups can't handle a very straightforward relative `node_modules` include which is why, TBH, I'm acting a little bitchy about this.

In general I don't update modules just for kicks. For utility stuff like this, I'd rather stick with something that I know works than chase updates.

The only argument interesting to me is file size, except that even that's predicated on more folks using 4 than 3 in production, and the site that this library was built for originally is still on 3.

**Comment by crubier** [comment]
Just coming here to say that I got the same bug, caused by this dependency on lodash 3. I do not use velocity on my project, it is a dependency of a react-storybook, and it is really annoying that my project dev experience is hampered by this. 

```
Module not found: Error: Can't resolve 'lodash/object/omit' in '/xxx/node_modules/velocity-react'
```

@finneganh , do you have any pointers to where react-storybook is using a non standard webpack setup ? Basically, where can I complain about this bug, if not here ? 

Sorry for the tone, but yeah, I just think you might not realize the impact of your decision.

**Comment by finneganh** [comment]
I'd recommend checking and seeing what's installed under
velocity-react/node_modules and poking in your lock file to see what it
says about lodash. Sounds more like your modules are not installed
correctly rather than a webpack config aliasing lodash or using a
non-standard module resolver.

**Comment by LyTranCong** [comment]
Why not move lodash to `peerDependencies`?

**Pull request closed without merging**
