### PR TITLE
Fix peerDependencies to be compatible with the 'react-transition-group' package

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
`react-transition-group` [requires](https://github.com/reactjs/react-transition-group/blob/master/package.json#L41-L42) `React ^15.0.0`

### CODE REVIEW

**Comment by finneganh** [comment]
Cool. I should be able to push this out tomorrow. I wonder how many folks are on pre-15.

**Comment by MichaelDeBoey** [comment]
This one requires a major bump I think...?

**Comment by finneganh** [comment]
I'll do a patch release. I admit to not being overly pedantic about semver and dependencies.

**Comment by finneganh** [comment]
Especially since the only reason to upgrade is to support more recent versions of React.

**Comment by MichaelDeBoey** [comment]
Yeah but older versions are deprecated now since the new release so everyone that uses `React 0.14.*` and has `velocity-react ^1.0.0` will now be forced to upgrade to `React v15.5`

**Comment by finneganh** [comment]
You're not forced to upgrade velocity-react. That being said, I think anyone developing apps without using a dependency lock file is asking for trouble already.

**Comment by MichaelDeBoey** [comment]
Not if everyone's using semver... 😛
Then there wouldn't be breaking changes (like `React` incompatibility)

**Comment by MichaelDeBoey** [comment]
But it's documented well in the CHANGELOG, so that allready something 🙂

**Comment by finneganh** [comment]
Thanks for having my back on the peer dependencies. It's clearly something I should have paid more attention to. Yay, open source!

**Comment by MichaelDeBoey** [comment]
No problem ;-)

**Pull request merged**
