### PR TITLE
Update deps to allow React 15

### PR DESCRIPTION
**Pull request by StevenLangbroek**
That's it :)

### CODE REVIEW

**Comment by StevenLangbroek** [comment]
Should `devDependencies` be specified the way I did now?

**Comment by finneganh** [comment]
I think it's ok to bump `devDependencies` to 15.

**Comment by finneganh** [comment]
Hopefully NPM is clever enough with that `react-addons-transition-group` to pull in the 0.14 version if your project is already using React 0.14.

**Comment by StevenLangbroek** [comment]
Should we wait for [this](https://twitter.com/reactjs/status/718252053441732612) and for `tween-state` to update its dependencies? If `tween-state` needs a deps bump let me know and I'll open a PR there too.

**Comment by finneganh** [comment]
I could go either way, depending upon how NPM complains. `tween-state` is only used for the demo, not the library itself.

**Comment by StevenLangbroek** [comment]
yeah, `devDeps` shouldn't give `EPEERINVALID` warnings, you're right. I don't think this library would be affected by the controlled input bug, so afaic this should be enough.

**Comment by liorbrauer** [comment]
👍 (Patiently waiting for this merge ;))

**Comment by finneganh** [comment]
@StevenLangbroek Can you give it a try to just put the devDependencies to 15?

**Comment by rtsao** [comment]
A more terse semver equivalent is `"0.14.x - 15.x"`.

**Comment by finneganh** [comment]
Switched to make the demo use React 15 in a separate PR. Thanks for opening this, though!

**Pull request closed without merging**
