### PR TITLE
React 15.5 / 16.0 support

### PR DESCRIPTION
**Pull request by finneganh**
- Switches to using React.Component subclasses
 - Switches to prop-types import
 - Switches to react-transition-group package
 - Removes uses of isMounted
 - Adds babel precompilation before distribution to support ES2015
   features

### CODE REVIEW

**Comment by finneganh** [comment]
Demo. Not bothering to figure out a classes way of doing the
react-tween-state mixin right now.

**Comment by danielo515** [comment]
I would love to see this merged and released.
Many thanks for this

**Comment by danielo515** [comment]
Nice ! When is the release planned ?

**Comment by finneganh** [comment]
@danielo515 Out now as v1.3.0.

**Comment by MichaelDeBoey** [comment]
@finneganh `prop-types` [requires](https://github.com/reactjs/prop-types#compatibility) `React 0.14.9` or `React ^15.3.0`

Fixed that in #197

**Comment by MichaelDeBoey** [comment]
@finneganh `react-transition-group` also [requires](https://github.com/reactjs/react-transition-group/blob/master/package.json#L41-L42) `React ^15.0.0`, so we need to drop support for `React 0.14.9` as well...

Fixed that in #199

**Pull request merged**
