### PR TITLE
Clarify documentation about VelocityComponent

### PR DESCRIPTION
**Pull request by david-rosales**
After trying a `VelocityComponent` with more than one child: 
```
<VelocityComponent animation={popAnimation} runOnMount={true}>
    <div>H</div>
    <div>I</div>
</VelocityComponent>
```
I received the following error `Warning: Failed propType: Invalid prop 'children' supplied to 'VelocityComponent', expected a single ReactElement. Check the render method of 'CardManager'.` I looked through the source code for `velocity-component.js` and the [comments on lines 146-148](https://github.com/twitter-fabric/velocity-react/blob/master/velocity-component.js#L146) seems to declare that there should only be one child rendered which doesn't seem to comply with the "Component to add Velocity animations to one **or more children**" part of the documentation.

### CODE REVIEW

**Comment by finneganh** [comment]
Sorry the documentation isn't very clear about this. I think the intent was to describe that you can use the `targetQuerySelector` prop to add the animation to multiple elements, which in this case are not strictly children but grandchildren or below.

**Comment by finneganh** [comment]
Let me see if I can convey that better.

**Comment by finneganh** [comment]
FWIW `VelocityComponent` requires a single child because it doesn't have a DOM wrapper element of its own.

**Comment by kevinrobinson** [comment]
@david-rosales Check this out: https://github.com/twitter-fabric/velocity-react/pull/102

**Comment by david-rosales** [comment]
This issue was fixed in #102 so I'm going to close this pull request.

**Pull request closed without merging**
